#!/bin/bash

APPLICATION_NAME=moose
# If $METHOD is not set, use opt
if [ -z $METHOD ]; then
  export METHOD=opt
fi

# set the cwd to the directory run_tests is in
cd `dirname $0` > /dev/null

MAKE_EXE="./$APPLICATION_NAME-unit-$METHOD"
CMAKE_EXE="../build/unit/moose_unit"

if [ -e "$CMAKE_EXE" ]; then
  EXECUTABLE="$CMAKE_EXE"
elif [ -e "$MAKE_EXE" ]; then
  EXECUTABLE="$MAKE_EXE"
else
  echo "Executable missing! Looked for '$MAKE_EXE' and '$CMAKE_EXE'"
  exit 1
fi

$EXECUTABLE $*

if [ $? -eq 0 ]
then
  echo "unit" >> ../test_results.log
else
  exit 1
fi

exit 0
